import FAQSection from "@/components/ui/FAQSection";

import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./animate.min.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Navbar />
        {children}
        <FAQSection />
        <Footer />
      </body>
    </html>
  );
}
